
- name: Create download folder
  ansible.builtin.file:
    path: '{{ storage.images.path }}/0'
    state: directory
  become: yes

- name: Download server images
  ansible.builtin.get_url:
    url: '{{ item.url }}'
    dest: '{{ storage.images.path }}/0/{{ item.os_file }}'
    checksum: '{{ item.checksum }}'
  with_items: '{{ os_images }}'
  when: 'item.state == "present"'
  become: yes