
- name: Get list users (JSON)
  ansible.builtin.command: pveum user list --output-format json
  register: cmd_users
  become: true

- name: Users on Fact
  ansible.builtin.set_fact:
    proxmox_users: "{{ cmd_users.stdout | from_json | community.general.groupby_as_dict('userid') }}"
