
drive_storage: local-lvm
drive_format: qcow2
linux_bridge: vmbr0

storage:
  images:
    id: ansible
    path: '/var/lib/vz/ansible/images'
  snippets: 
    id: ansible
    path: '/var/lib/vz/ansible/snippets'

machines:
  - name: debian-11
    vmid: 50011
    node: pve
    image_file: debian-11-generic-amd64.qcow2
    state: template

os_images:
  - name: Debian11
    description: 'Debian 11 (bullseye)'
    os_file: debian-11-generic-amd64.qcow2
    url: 'https://cloud.debian.org/images/cloud/bullseye/latest/debian-11-generic-amd64.qcow2'
    checksum: sha512:50b2b6b64327c3de91d00f912436e355b1cd552db8cf6c117568afcd07295867e44c1163eb2990819fc71b8f08bdd6c1221b3f5d4c7d1792477542716d1a7b17
    state: present
